name: Build Vanilla

on:
  push:
    #tags:
    #  - vanilla-*

jobs:
  build-vanilla:
    name: build vanilla
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish TShock
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: didstopia/terraria
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: vanilla/Dockerfile
          workdir: vanilla
          tags: "vanilla-latest"
          tag_names: true
